### ISSUE TITLE
light visible from behind the walls

### ISSUE THREAD

**Issue by b-abdollahi** [sessamekesh/IndigoCS-webgl-tutorials#3]
Hi Kamaron!

I watched your shadow mapping tutorial today, first of all, great job! 

I have kind of a question/issue about your code. 
I did the following:
 - turned the CULL_FACE off during rendering (only ON during _GenerateShadowMap).
 - then I moved the camera out of the room. 
 - now if I look at the walls from outside, I still see the effect of lights and shadows.
Is there any way to avoid this? 

I am working on a project that has multiple rooms. I don't want the light from one room being visible in others which is logical. Project is for the university and I am not allowed to use 3rd party software (only glmatrix). 

Many Thanks 
Behzad

**Comment by sessamekesh** [comment]
One thing you could do is to separate them: Use different models for the walls of room 1 than you do for the walls of room 2, generate the lights and shadows for room 1 and then render room 1, then generate the lights and shadows for room 2 and render room 2. Switch out the light sources and shadow maps for each.

One negative effect this will have is that there might be some artifacts at the boundaries - e.g., there won't be a strip of light cast from a bright room 1 into a dim room 2 from an open door frame.

I haven't tweaked this demo to have two rooms, so I haven't actually tried that - but that is where I would start. Let me know (you can comment again on this issue) if that works/doesn't work, or you have further questions.

**Comment by b-abdollahi** [comment]
Thanks! It worked well. Do you have any plans for further webgl tutorials? like for particle system?

**Comment by sessamekesh** [comment]
Sweet! Glad to hear it.

What I'm doing next is a video series on making a 3D web game from scratch - using gl-matrix for the math, _maybe_ something like jQuery for interacting the DOM but otherwise no libraries. There's a long list of things I'd _like_ to get to, which ones I actually cover in this next series depends on how well they fit: blending (transparency), particle effects, reflections, GUIs, and animated models, specifically. I'll also be covering a lot of non-WebGL stuff, like audio, input handling, probably DOM interactions... if it fits, I'd love to put in some stuff about service workers and/or WebAssembly too. I don't want this to be a crazy long video series, so I have to be a bit more careful in budgeting the tutorial time for this one.

I'm still planning those videos out, I've gone through two proof of concept games so far that I decided against doing. I really like the current game I'm working on, I think it'll let me focus on the interesting stuff on-screen, while still making a neat game. I'm about 20% done with it, once I'm done and satisfied I'll be able to start planning and recording the videos for that.

After the game series, I'm not sure what I'm going to do - I've thought about doing particle systems and animating characters as mini-series on their own. There's also WebGL 2, which brings in a few things that are currently impossible / infeasible with WebGL (like deferred rendering), so I've thought about covering that. I think doing one on service workers would be good too - WebGL apps often use quite a lot of big resources, and service workers let you do some pretty clever things with the browser cache.

**Comment by b-abdollahi** [comment]
Hi again :) how are things going with the new videos? once I saw your live tutorial, but it was 5AM in my timezone so I went back to sleep :D 

I wanted to ask you if it is possible that you answer some conceptual questions about webgl? 

for example, in my project, i have 3 rooms and each of them have different lights. I want to move an object between rooms, my Object was defined in room Nr. 1, when it goes to room Nr. 2, it still reflects the lights in the first room. I have no experience with graphics programming and that why I have a hard time understanding some stuff. It would be great if you give me some hints. my email: b.abdollahi@gmail.com

Best regards, Behzad

**Comment by b-abdollahi** [comment]
Hi again! I just realized a way to do it. It should work, but i will continue working on it tomorrow :)

**Comment by sessamekesh** [comment]
No worries, sorry I didn't get back to it sooner - I was out of town for work stuff, just got back to my computer. Videos are going well, I could probably start recording in the next week or so, but I'll probably wait a bit longer until I have more of the code written. Once I start putting them up, I don't want to have to delay very long between them.
