### ISSUE TITLE
Using fetch().then() and Promises to avoid nested callback

### ISSUE THREAD

**Issue by xxMrPHDxx** [sessamekesh/IndigoCS-webgl-tutorials#5]
Promises and fetch is one of ES6 features and should be used to chain asynchronously.

Here's an example:
```
Promise.all([
	loadText('shader/vs.glsl'),
	loadText('shader/fs.glsl'),
	loadJSON('sphere.json'),
	loadImage('tex/soccer.png'),
	loadImage('tex/crate.png')
]).then(([vertexShaderText,fragmentShaderText,sphereJson,soccerImage,crateImage])=>{
	let vertexShader = new Shader.VertexShader(gl).create(vertexShaderText);
	let fragmentShader = new Shader.FragmentShader(gl).create(fragmentShaderText);
	let shaderProgram = new ShaderProgram(gl).attachShader(vertexShader,fragmentShader);
	return Promise.all([
		new Ball(gl,shaderProgram,sphereJson,soccerImage),
		new Crate(gl,shaderProgram,crateImage)
	])
}).then(([soccerObj, crateObj]) => {
	ball = soccerObj;
	crate = crateObj;
	setTimeout(start,1000);
});
```

You can find the full code [here](https://github.com/xxMrPHDxx/WebGL/)

**Comment by sessamekesh** [comment]
Yes! The old callback hell style of JS coding is something I've never been a fan of... I was on the fence to use `async` (a pre-ES6 JavaScript library that also attempted to mitigate this problem) here as well, but ultimately decided against it.

I've left the code as is for the past two years because this code was put up to accompany YouTube videos that were recorded and published before ES6 promises were fully supported by browsers. I should really just go back and update them to at least use promises, since this is a much better way of doing things overall - I think that's a reasonable change to be made, especially since it's in the resource loading code and not the drawing code itself.
